### ISSUE TITLE
GPL License question

### ISSUE THREAD

**Issue by mdda** [nasimrahaman/speedrun#5]
Your library seems like a very attractive way to organise experiments for reproducibility, etc.  

But I am a little concerned about having my code subclass your GPL3 classes (```BaseExperiment```, etc) - which (according to sources like https://stackoverflow.com/questions/999468/question-on-importing-a-gpled-python-library-in-commercial-code) might make my training code (and, by extension, my model code) GPL3 licensed.

Is that the intention of your license choice?  I see that ```inferno``` itself is Apache, which is more friendly to people building commercial models.

**Comment by nasimrahaman** [comment]
Thanks for raising this - I'll change the license to Apache.

**Comment by nasimrahaman** [comment]
@mdda Fixed. 👍
